name: build and test
on:
  push:
    branches: [ main ]
    paths-ignore: [ '**.md' ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ '**.md' ]
jobs:
  build-and-test:
    name: build-and-test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet-version: [ '6.0.x' ]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Build
      working-directory: ./InternetArchive.NET.Tests
      run: dotnet build --configuration Release
    - name: Test
      working-directory: ./InternetArchive.NET.Tests
      env:
        emailAddress: ${{ secrets.EMAILADDRESS }}
        accessKey: ${{ secrets.ACCESSKEY }}
        secretKey: ${{ secrets.SECRETKEY }}
        testItem: etc-test-item
        testCollection: etc-test-collection
        testList: etc-test-list
      run: 
        dotnet test --configuration Release --logger "console;verbosity=normal"

