name: update nuget
on:
  workflow_dispatch
env:
  DOTNET_VERSION: '6.0.x'
jobs:
  update-nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
    - name: Pack
      working-directory: ./InternetArchive.NET
      run: dotnet pack --configuration Release --output package
    - name: Push
      working-directory: ./InternetArchive.NET/package
      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGETKEY }}
